{% set name = "gdbm" %}
{% set version = "1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ftp://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha1: 0f1056ab3beb1bf09dad06f8083f2c79716a5b1b

build:
  number: 1
  run_exports:
    # Please see ABI report
    # https://abi-laboratory.pro/index.php?view=timeline&l=gdbm
    - {{ pin_subpackage(name, max_pin='x.x') }}
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - readline

test:
  commands:
    - gdbm_dump --version
    - gdbm_load --version
    - gdbmtool --version

about:
  home: https://www.gnu.org.ua/software/gdbm/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: >
    A library of database functions that use extensible hashing and works
    similar to the standard UNIX dbm functions.

extra:
  recipe-maintainers:
    - hmaarrfk
    - jakirkham
