{% set name = "gdbm" %}
{% set version = "1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8822cb4769e2d759c828c06f196614936c88c141c3132b18252fe25c2b635ce
  patches:
    # From https://github.com/spack/spack/commit/6d7daf0def6b8c432b5e79d48c96f29faf3d2db9
    - gdbm_gcc_10.patch
    - osx_arm64.patch   # [osx and arm64]

build:
  number: 4
  missing_dso_whitelist:  # [linux and s390x]
    - $RPATH/ld64.so.1    # [linux and s390x]
  run_exports:
    # Please see ABI report
    # https://abi-laboratory.pro/index.php?view=timeline&l=gdbm
    - {{ pin_subpackage(name, max_pin='x.x') }}
  skip: True  # [win]

requirements:
  build:
    - libtool   # [unix]
    - {{ compiler('c') }}
    - make
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - readline

test:
  commands:
    - gdbm_dump --version
    - gdbm_load --version
    - gdbmtool --version

about:
  home: https://www.gnu.org.ua/software/gdbm/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: >
    A library of database functions that use extensible hashing and works
    similar to the standard UNIX dbm functions.
  doc_url: https://git.gnu.org.ua/gdbm.git/tree/
  dev_url: https://git.gnu.org.ua/gdbm.git/tree/

extra:
  recipe-maintainers:
    - hmaarrfk
    - jakirkham
